SELECT 
	--TOP 10
	--TOP 1 PERCENT --RETURN 1 % OF ROWS
	--NECESSITA USAR ORDER BY, E IRÁ RETORNAR ROWS A MAIS,
	--CASO O VALOR DA COLUNA NO ORDER FOR IGUAL
	--TOP 4 WITH TIES 
	*
FROM NOTA_FISCAL

-- EXEMPLO USO DO WITH TIES
CREATE TABLE T(
	ID INT NOT NULL PRIMARY KEY,
	PRECO FLOAT
)
GO

INSERT INTO T VALUES(1, 5)
INSERT INTO T VALUES(2, 10)
INSERT INTO T VALUES(3, 10)
INSERT INTO T VALUES(4, 20)

SELECT TOP 2 WITH TIES
	*
FROM T
ORDER BY PRECO

/* RESULT IN, NOTE QUE, TEM O TOP 2, SÓ QUE, COMO O PRECO É IGUAL,
IRÁ RETORNAR OS REGISTROS QUE SÃO IGUAIS ( NO ULTIMO )
1	5
2	10
3	10
*/

